In [ ]:
import pandas as pd
from sentence_transformers import SentenceTransformer, util

Lectures des abstract pour IEEE Xplore

In [ ]:
df=pd.read_csv("IEEE_Scrapping.csv",sep=";")

Chargement du modèle LLM

In [ ]:
model = SentenceTransformer('all-MiniLM-L6-v2')

In [ ]:
similarity_scores=[]
sentence="Reinforcement learning for trading"
for i in df["Abstracts"]:
    abstract = i

    embeddings = model.encode([sentence, abstract], convert_to_tensor=True)
    similarity = util.cos_sim(embeddings[0], embeddings[1])

    print(f"Similarity score: {similarity.item():.4f}")
    similarity_scores.append(similarity.item())

Similarity score: 0.5351
Similarity score: 0.5258
Similarity score: 0.6530
Similarity score: 0.6592
Similarity score: 0.6416
Similarity score: 0.6003
Similarity score: 0.6355
Similarity score: 0.6203
Similarity score: 0.6557
Similarity score: 0.6215
Similarity score: 0.5988
Similarity score: 0.5633
Similarity score: 0.6150
Similarity score: 0.5649
Similarity score: 0.6177
Similarity score: 0.7844
Similarity score: 0.4609
Similarity score: 0.7405
Similarity score: 0.6201
Similarity score: 0.6019
Similarity score: 0.6577
Similarity score: 0.6536
Similarity score: 0.6653
Similarity score: 0.6535
Similarity score: 0.6609
Similarity score: 0.6884
Similarity score: 0.5840
Similarity score: 0.4907
Similarity score: 0.6114
Similarity score: 0.6497
Similarity score: 0.5935
Similarity score: 0.5790
Similarity score: 0.6533
Similarity score: 0.6515
Similarity score: 0.6865
Similarity score: 0.6907
Similarity score: 0.3920
Similarity score: 0.6580
Similarity score: 0.6006
Similarity score: 0.4956
Similarity score: 0.6252
Similarity score: 0.6534
Similarity score: 0.7071
Similarity score: 0.7023
Similarity score: 0.5949
Similarity score: 0.5061
Similarity score: 0.5816
Similarity score: 0.5284
Similarity score: 0.7249
Similarity score: 0.6956
Similarity score: 0.5076
Similarity score: 0.6457
Similarity score: 0.7125
Similarity score: 0.6055
Similarity score: 0.6341
Similarity score: 0.6591
Similarity score: 0.6676
Similarity score: 0.7329
Similarity score: 0.5429
Similarity score: 0.6432
Similarity score: 0.6488
Similarity score: 0.7008
Similarity score: 0.6878
Similarity score: 0.5550
Similarity score: 0.4857
Similarity score: 0.7030
Similarity score: 0.6297
Similarity score: 0.6830
Similarity score: 0.4679
Similarity score: 0.6570
Similarity score: 0.5785
Similarity score: 0.6175
Similarity score: 0.6917
Similarity score: 0.6344
Similarity score: 0.6153
Similarity score: 0.5155
Similarity score: 0.6471
Similarity score: 0.6491
Similarity score: 0.4941
Similarity score: 0.6294
Similarity score: 0.4378
Similarity score: 0.6558
Similarity score: 0.6669
Similarity score: 0.6547
Similarity score: 0.5867
Similarity score: 0.5508
Similarity score: 0.6263
Similarity score: 0.5942
Similarity score: 0.6641
Similarity score: 0.6088
Similarity score: 0.4907
Similarity score: 0.5591
Similarity score: 0.5958
Similarity score: 0.5620
Similarity score: 0.6542
Similarity score: 0.4474
Similarity score: 0.4487
Similarity score: 0.7035
Similarity score: 0.6117
Similarity score: 0.5603
Similarity score: 0.5459
Similarity score: 0.5975
Similarity score: 0.6018
Similarity score: 0.6351
Similarity score: 0.3312
Similarity score: 0.4708
Similarity score: 0.5620
Similarity score: 0.6032
Similarity score: 0.4325
Similarity score: 0.5957
Similarity score: 0.6432
Similarity score: 0.5192
Similarity score: 0.4448
Similarity score: 0.6221
Similarity score: 0.4569
Similarity score: 0.4682
Similarity score: 0.6142
Similarity score: 0.6856
Similarity score: 0.6318
Similarity score: 0.7290
Similarity score: 0.6992
Similarity score: 0.5389
Similarity score: 0.6185
Similarity score: 0.4416
Similarity score: 0.6998
Similarity score: 0.4454
Similarity score: 0.6288
Similarity score: 0.4814
Similarity score: 0.4475
Similarity score: 0.5433
Similarity score: 0.5143
Similarity score: 0.4670
Similarity score: 0.5461
Similarity score: 0.4990
Similarity score: 0.4792
Similarity score: 0.4509
Similarity score: 0.6669
Similarity score: 0.5446
Similarity score: 0.5557
Similarity score: 0.4861
Similarity score: 0.4756
Similarity score: 0.4597
Similarity score: 0.5265
Similarity score: 0.6518
Similarity score: 0.4035

In [ ]:
df["similarity_scores"]=similarity_scores

Conservation des articles ayant un score de similarité supérieur à 0.65

In [ ]:
articles_interessant=df[df["similarity_scores"]>0.65]

Enregistrement des articles sous CSV

In [ ]:
articles_interessant.to_csv("Meilleurs_Articles.csv",sep=";",index=False)

In [ ]:
articles_interessant.shape

(43, 4)

Lecture des abstracts intéréssant GOOGLE SCholar

In [ ]:
df2=pd.read_csv("articles_int_google_scholar.csv",sep=";")

In [ ]:
df2

,url,abstract
0,https://arxiv.org/abs/1911.10107,We adopt Deep Reinforcement Learning algorithm...
1,https://dl.acm.org/doi/abs/10.1145/3582560,Quantitative trading QT which refers to the...
2,https://arxiv.org/abs/2106.00123,Algorithmic stock trading has become a staple ...
3,https://www.sciencedirect.com/science/article/...,Highlights Reinforcement learning RL forma...
4,https://arxiv.org/abs/1807.02787,An automatic program that generates constant p...
5,https://ieeexplore.ieee.org/abstract/document/...,In algorithmic trading feature extraction and...
6,https://aaai.org/ojs/index.php/AAAI/article/vi...,In recent years considerable efforts have bee...
7,https://ieeexplore.ieee.org/abstract/document/...,Can we train the computer to beat experienced ...
8,https://arxiv.org/abs/2011.09607,As deep reinforcement learning DRL has been ...
9,https://link.springer.com/article/10.1007/s006...,The role of the stock market across the overal...
10,https://ieeexplore.ieee.org/abstract/document/...,In this paper we explore the role of emerging...
11,https://ieeexplore.ieee.org/abstract/document/...,In practice the parameters of control policie...
12,https://ieeexplore.ieee.org/abstract/document/...,Peer to peer P2P transactive energy trading ...
13,https://link.springer.com/chapter/10.1007/978-...,Trading strategies are in constant transformat...
14,https://www.atlantis-press.com/proceedings/icb...,Reinforcement learning has achieved superhuman...
15,https://link.springer.com/chapter/10.1007/978-...,We optimized the Sure Fire statistical arbitra...
16,https://dr.ntu.edu.sg/handle/10356/183967,Reinforcement Learning RL has emerged as a p...

In [ ]:
similarity_scores=[]
sentence="Reinforcement learning for trading"
for i in df2["abstract"]:
    abstract = i

    embeddings = model.encode([sentence, abstract], convert_to_tensor=True)
    similarity = util.cos_sim(embeddings[0], embeddings[1])

    print(f"Similarity score: {similarity.item():.4f}")
    similarity_scores.append(similarity.item())

Similarity score: 0.6015
Similarity score: 0.6537
Similarity score: 0.6977
Similarity score: 0.6963
Similarity score: 0.6507
Similarity score: 0.6534
Similarity score: 0.6693
Similarity score: 0.6418
Similarity score: 0.6202
Similarity score: 0.6538
Similarity score: 0.5104
Similarity score: 0.3932
Similarity score: 0.5140
Similarity score: 0.6036
Similarity score: 0.6777
Similarity score: 0.6364
Similarity score: 0.5364

Conservation des articles ayant un score de similarité supérieur à 0.6 et extraction des ces articles

In [ ]:
df2["similarity_scores"]=similarity_scores
articles_interessant2=df2[df2["similarity_scores"]>0.6]
articles_interessant2.to_csv("Meilleurs_Articles_Google_Scholar.csv",sep=";",index=False)

In [ ]:
articles_interessant2.shape

(13, 3)

In [ ]:
articles_interessant2

,url,abstract,similarity_scores
0,https://arxiv.org/abs/1911.10107,We adopt Deep Reinforcement Learning algorithm...,0.601451
1,https://dl.acm.org/doi/abs/10.1145/3582560,Quantitative trading QT which refers to the...,0.653721
2,https://arxiv.org/abs/2106.00123,Algorithmic stock trading has become a staple ...,0.697744
3,https://www.sciencedirect.com/science/article/...,Highlights Reinforcement learning RL forma...,0.696328
4,https://arxiv.org/abs/1807.02787,An automatic program that generates constant p...,0.650731
5,https://ieeexplore.ieee.org/abstract/document/...,In algorithmic trading feature extraction and...,0.653412
6,https://aaai.org/ojs/index.php/AAAI/article/vi...,In recent years considerable efforts have bee...,0.669285
7,https://ieeexplore.ieee.org/abstract/document/...,Can we train the computer to beat experienced ...,0.641822
8,https://arxiv.org/abs/2011.09607,As deep reinforcement learning DRL has been ...,0.620174
9,https://link.springer.com/article/10.1007/s006...,The role of the stock market across the overal...,0.653850
13,https://link.springer.com/chapter/10.1007/978-...,Trading strategies are in constant transformat...,0.603569
14,https://www.atlantis-press.com/proceedings/icb...,Reinforcement learning has achieved superhuman...,0.677697
15,https://link.springer.com/chapter/10.1007/978-...,We optimized the Sure Fire statistical arbitra...,0.636369